accounts:
  - name: oliver
    coins: ["20000token", "200000000stake"]
  - name: harry
    coins: ["10000token", "100000000stake"]
  - name: liam
    coins: ["10000token", "100000000stake"]
  - name: lucas
    coins: ["10000token", "100000000stake"]
  - name: declan
    coins: ["10000token", "100000000stake"]
  - name: elliot
    coins: ["10000token", "100000000stake"]
  - name: owen
    coins: ["10000token", "100000000stake"]
  - name: oskar
    coins: ["10000token", "100000000stake"]
  - name: hazel
    coins: ["20000token", "200000000stake"]
  - name: lily
    coins: ["10000token", "100000000stake"]
  - name: sophia
    coins: ["10000token", "100000000stake"]
  - name: isabella
    coins: ["10000token", "100000000stake"]
  - name: zoe
    coins: ["10000token", "100000000stake"]
  - name: aria
    coins: ["10000token", "100000000stake"]
  
validator:
  name: oliver
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: harry
  coins: ["5token", "100000stake"]
